# Generated by Django 2.1.4 on 2019-05-12 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
