# Generated by Django 2.1.4 on 2019-07-11 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('black_mage', '0003_auto_20190710_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='topic_portal',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='black_mage.Portal'),
            preserve_default=False,
        ),
    ]
